"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-07-23 23:49:08.878867
"""
from datetime import UTC, datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('singleton_key', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('password_version', sa.Integer(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('singleton_key = 1', name='ck_admin_singleton'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('singleton_key')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_username'), ['username'], unique=True)

    op.create_table('app_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cron', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_asset_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_app_setting_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=2048), nullable=True),
    sa.Column('checksum_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_purged_at'), ['purged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_sha256'), ['sha256'], unique=True)

    op.create_table('backup_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('active_slot', sa.Integer(), nullable=True),
    sa.Column('pending_slot', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('status_reason', sa.String(length=255), nullable=True),
    sa.Column('document_total', sa.Integer(), nullable=False),
    sa.Column('document_succeeded', sa.Integer(), nullable=False),
    sa.Column('document_partial', sa.Integer(), nullable=False),
    sa.Column('document_failed', sa.Integer(), nullable=False),
    sa.Column('asset_total', sa.Integer(), nullable=False),
    sa.Column('asset_succeeded', sa.Integer(), nullable=False),
    sa.Column('asset_failed', sa.Integer(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('waiting_quota_credentials', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merged_from', sa.JSON(), nullable=False),
    sa.Column('cleanup_stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('active_slot IS NULL OR active_slot = 1', name='ck_backup_job_active_slot'),
    sa.CheckConstraint('pending_slot IS NULL OR pending_slot = 1', name='ck_backup_job_pending_slot'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_slot', name='uq_backup_job_active_slot'),
    sa.UniqueConstraint('pending_slot', name='uq_backup_job_pending_slot')
    )
    with op.batch_alter_table('backup_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_job_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_job_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_job_trigger'), ['trigger'], unique=False)

    op.create_table('idempotency_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_key', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('idempotency_key', sa.String(length=36), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_key', 'method', 'path', 'idempotency_key', name='uq_idempotency_scope')
    )
    with op.batch_alter_table('idempotency_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_record_expires_at'), ['expires_at'], unique=False)

    op.create_table('login_attempt',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key_hash')
    )
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempt_blocked_until'), ['blocked_until'], unique=False)

    op.create_table('rate_limit_bucket',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('rate_limit_limit', sa.Integer(), nullable=True),
    sa.Column('rate_limit_remaining', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_allowed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url', 'subject_type', 'subject_id', name='uq_rate_bucket_subject')
    )
    with op.batch_alter_table('rate_limit_bucket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_bucket_next_allowed_at'), ['next_allowed_at'], unique=False)

    op.create_table('repository',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('normalized_base_url', sa.String(length=2048), nullable=False),
    sa.Column('yuque_book_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('namespace', sa.String(length=512), nullable=True),
    sa.Column('repo_type', sa.String(length=64), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('content_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('safe_watermark', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('toc_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_base_url', 'yuque_book_id', name='uq_repository_remote')
    )
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_selected'), ['selected'], unique=False)

    op.create_table('retention_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_retention_policy_singleton'),
    sa.CheckConstraint('retention_days > 0', name='ck_retention_days_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_worker_heartbeat_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yuque_credential',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('encrypted_token', sa.LargeBinary(), nullable=False),
    sa.Column('token_nonce', sa.LargeBinary(length=12), nullable=False),
    sa.Column('token_suffix', sa.String(length=4), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=True),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('verification_valid', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit_limit', sa.Integer(), nullable=True),
    sa.Column('rate_limit_remaining', sa.Integer(), nullable=True),
    sa.Column('rate_limit_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pause_reason', sa.String(length=255), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('yuque_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yuque_credential_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_yuque_credential_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_yuque_credential_next_retry_at'), ['next_retry_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_yuque_credential_status'), ['status'], unique=False)
        batch_op.create_index('uq_yuque_credential_active_name', ['name'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('admin_session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('password_version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_session_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_session_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_session_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_session_token_hash'), ['token_hash'], unique=True)

    op.create_table('backup_subtask',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('document_total', sa.Integer(), nullable=False),
    sa.Column('document_completed', sa.Integer(), nullable=False),
    sa.Column('document_succeeded', sa.Integer(), nullable=False),
    sa.Column('document_partial', sa.Integer(), nullable=False),
    sa.Column('document_failed', sa.Integer(), nullable=False),
    sa.Column('asset_total', sa.Integer(), nullable=False),
    sa.Column('asset_succeeded', sa.Integer(), nullable=False),
    sa.Column('asset_failed', sa.Integer(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_issue', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['yuque_credential.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['backup_job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'repository_id', name='uq_subtask_job_repository')
    )
    with op.batch_alter_table('backup_subtask', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_subtask_credential_id'), ['credential_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_subtask_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_subtask_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_subtask_status'), ['status'], unique=False)

    op.create_table('deletion_tombstone',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('yuque_book_id', sa.String(length=128), nullable=False),
    sa.Column('yuque_doc_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('original_path', sa.String(length=2048), nullable=False),
    sa.Column('deleted_slug', sa.String(length=512), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_job_id', sa.String(length=36), nullable=False),
    sa.Column('cleanup_job_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_job_id'], ['backup_job.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url', 'yuque_book_id', 'yuque_doc_id', 'deleted_at', name='uq_tombstone_remote')
    )
    with op.batch_alter_table('deletion_tombstone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deletion_tombstone_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_tombstone_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_tombstone_title'), ['title'], unique=False)

    op.create_table('job_trigger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['backup_job.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_job_trigger_idempotency')
    )
    with op.batch_alter_table('job_trigger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_trigger_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_trigger_status'), ['status'], unique=False)

    op.create_table('operation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['yuque_credential.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_credential_id'), ['credential_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_status'), ['status'], unique=False)
        batch_op.create_index('uq_operation_active_credential_type', ['credential_id', 'type'], unique=True, sqlite_where=sa.text("status IN ('queued', 'running', 'waiting_quota')"))

    op.create_table('repository_credential',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('access_status', sa.String(length=32), nullable=False),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['yuque_credential.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'credential_id', name='uq_repository_credential')
    )
    with op.batch_alter_table('repository_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_credential_credential_id'), ['credential_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_credential_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index('uq_repository_primary_credential', ['repository_id'], unique=True, sqlite_where=sa.text('is_primary IS 1'))

    op.create_table('toc_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('remote_id', sa.String(length=255), nullable=False),
    sa.Column('parent_remote_id', sa.String(length=255), nullable=True),
    sa.Column('yuque_doc_id', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'remote_id', name='uq_toc_remote')
    )
    with op.batch_alter_table('toc_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toc_item_parent_remote_id'), ['parent_remote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_toc_item_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_toc_item_yuque_doc_id'), ['yuque_doc_id'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('yuque_doc_id', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=True),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('original_path', sa.String(length=2048), nullable=False),
    sa.Column('toc_item_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_slug', sa.String(length=512), nullable=True),
    sa.Column('latest_successful_version_id', sa.String(length=36), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['toc_item_id'], ['toc_item.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'yuque_doc_id', name='uq_document_remote')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_latest_successful_version_id'), ['latest_successful_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_toc_item_id'), ['toc_item_id'], unique=False)

    op.create_table('document_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('remote_version_id', sa.String(length=128), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('completeness', sa.String(length=16), nullable=False),
    sa.Column('raw_response_path', sa.String(length=2048), nullable=True),
    sa.Column('raw_body_path', sa.String(length=2048), nullable=True),
    sa.Column('preview_path', sa.String(length=2048), nullable=True),
    sa.Column('manifest_path', sa.String(length=2048), nullable=True),
    sa.Column('content_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('normalized_metadata', sa.JSON(), nullable=False),
    sa.Column('resource_total', sa.Integer(), nullable=False),
    sa.Column('resource_downloaded', sa.Integer(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('source_job_id', sa.String(length=36), nullable=False),
    sa.Column('remote_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_job_id'], ['backup_job.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'content_hash', name='uq_document_version_hash')
    )
    with op.batch_alter_table('document_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_version_completeness'), ['completeness'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_version_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_version_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_version_purged_at'), ['purged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_version_source_job_id'), ['source_job_id'], unique=False)

    op.create_table('queue_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('last_error_message', sa.String(length=1024), nullable=True),
    sa.Column('operation_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('subtask_id', sa.String(length=36), nullable=True),
    sa.Column('credential_id', sa.String(length=36), nullable=True),
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempt_count >= 0', name='ck_queue_attempt_nonnegative'),
    sa.ForeignKeyConstraint(['credential_id'], ['yuque_credential.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['backup_job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtask_id'], ['backup_subtask.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_queue_idempotency')
    )
    with op.batch_alter_table('queue_item', schema=None) as batch_op:
        batch_op.create_index('ix_queue_claim', ['status', 'available_at', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_item_available_at'), ['available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_item_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_item_credential_id'), ['credential_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_item_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_item_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_item_lease_owner'), ['lease_owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_item_lease_until'), ['lease_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_item_next_retry_at'), ['next_retry_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_item_operation_id'), ['operation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_item_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_item_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_item_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_item_subtask_id'), ['subtask_id'], unique=False)

    op.create_table('sync_checkpoint',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checkpoint_key', sa.String(length=255), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('safe_watermark', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkpoint_key', name='uq_checkpoint_key')
    )
    with op.batch_alter_table('sync_checkpoint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_checkpoint_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_checkpoint_repository_id'), ['repository_id'], unique=False)

    op.create_table('backup_issue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('subtask_id', sa.String(length=36), nullable=True),
    sa.Column('credential_id', sa.String(length=36), nullable=True),
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('document_title', sa.String(length=512), nullable=True),
    sa.Column('asset_type', sa.String(length=32), nullable=True),
    sa.Column('safe_url', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('first_occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credential_id'], ['yuque_credential.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['backup_job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subtask_id'], ['backup_subtask.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['document_version.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_issue_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_issue_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_issue_credential_id'), ['credential_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_issue_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_issue_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_issue_last_occurred_at'), ['last_occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_issue_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_issue_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_issue_subtask_id'), ['subtask_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_issue_version_id'), ['version_id'], unique=False)

    op.create_table('version_asset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('safe_url', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('declared_size', sa.BigInteger(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issue_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['document_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('version_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_version_asset_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_version_asset_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_version_asset_version_id'), ['version_id'], unique=False)

    now = datetime.now(UTC)
    op.bulk_insert(
        sa.table(
            'app_setting',
            sa.column('id', sa.Integer()),
            sa.column('cron', sa.String()),
            sa.column('timezone', sa.String()),
            sa.column('schedule_enabled', sa.Boolean()),
            sa.column('max_asset_size_bytes', sa.BigInteger()),
            sa.column('version', sa.Integer()),
            sa.column('updated_at', sa.DateTime(timezone=True)),
        ),
        [{
            'id': 1,
            'cron': '0 2 * * *',
            'timezone': 'Asia/Shanghai',
            'schedule_enabled': True,
            'max_asset_size_bytes': 524_288_000,
            'version': 1,
            'updated_at': now,
        }],
    )
    op.bulk_insert(
        sa.table(
            'retention_policy',
            sa.column('id', sa.Integer()),
            sa.column('retention_days', sa.Integer()),
            sa.column('updated_at', sa.DateTime(timezone=True)),
        ),
        [{'id': 1, 'retention_days': 15, 'updated_at': now}],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_version_asset_version_id'))
        batch_op.drop_index(batch_op.f('ix_version_asset_status'))
        batch_op.drop_index(batch_op.f('ix_version_asset_asset_id'))

    op.drop_table('version_asset')
    with op.batch_alter_table('backup_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_issue_version_id'))
        batch_op.drop_index(batch_op.f('ix_backup_issue_subtask_id'))
        batch_op.drop_index(batch_op.f('ix_backup_issue_repository_id'))
        batch_op.drop_index(batch_op.f('ix_backup_issue_level'))
        batch_op.drop_index(batch_op.f('ix_backup_issue_last_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_backup_issue_job_id'))
        batch_op.drop_index(batch_op.f('ix_backup_issue_document_id'))
        batch_op.drop_index(batch_op.f('ix_backup_issue_credential_id'))
        batch_op.drop_index(batch_op.f('ix_backup_issue_code'))
        batch_op.drop_index(batch_op.f('ix_backup_issue_asset_id'))

    op.drop_table('backup_issue')
    with op.batch_alter_table('sync_checkpoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_checkpoint_repository_id'))
        batch_op.drop_index(batch_op.f('ix_sync_checkpoint_document_id'))

    op.drop_table('sync_checkpoint')
    with op.batch_alter_table('queue_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_item_subtask_id'))
        batch_op.drop_index(batch_op.f('ix_queue_item_status'))
        batch_op.drop_index(batch_op.f('ix_queue_item_repository_id'))
        batch_op.drop_index(batch_op.f('ix_queue_item_priority'))
        batch_op.drop_index(batch_op.f('ix_queue_item_operation_id'))
        batch_op.drop_index(batch_op.f('ix_queue_item_next_retry_at'))
        batch_op.drop_index(batch_op.f('ix_queue_item_lease_until'))
        batch_op.drop_index(batch_op.f('ix_queue_item_lease_owner'))
        batch_op.drop_index(batch_op.f('ix_queue_item_job_id'))
        batch_op.drop_index(batch_op.f('ix_queue_item_document_id'))
        batch_op.drop_index(batch_op.f('ix_queue_item_credential_id'))
        batch_op.drop_index(batch_op.f('ix_queue_item_category'))
        batch_op.drop_index(batch_op.f('ix_queue_item_available_at'))
        batch_op.drop_index('ix_queue_claim')

    op.drop_table('queue_item')
    with op.batch_alter_table('document_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_version_source_job_id'))
        batch_op.drop_index(batch_op.f('ix_document_version_purged_at'))
        batch_op.drop_index(batch_op.f('ix_document_version_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_version_created_at'))
        batch_op.drop_index(batch_op.f('ix_document_version_completeness'))

    op.drop_table('document_version')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_toc_item_id'))
        batch_op.drop_index(batch_op.f('ix_document_title'))
        batch_op.drop_index(batch_op.f('ix_document_slug'))
        batch_op.drop_index(batch_op.f('ix_document_repository_id'))
        batch_op.drop_index(batch_op.f('ix_document_path'))
        batch_op.drop_index(batch_op.f('ix_document_latest_successful_version_id'))
        batch_op.drop_index(batch_op.f('ix_document_deleted_at'))

    op.drop_table('document')
    with op.batch_alter_table('toc_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toc_item_yuque_doc_id'))
        batch_op.drop_index(batch_op.f('ix_toc_item_repository_id'))
        batch_op.drop_index(batch_op.f('ix_toc_item_parent_remote_id'))

    op.drop_table('toc_item')
    with op.batch_alter_table('repository_credential', schema=None) as batch_op:
        batch_op.drop_index('uq_repository_primary_credential', sqlite_where=sa.text('is_primary IS 1'))
        batch_op.drop_index(batch_op.f('ix_repository_credential_repository_id'))
        batch_op.drop_index(batch_op.f('ix_repository_credential_credential_id'))

    op.drop_table('repository_credential')
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.drop_index('uq_operation_active_credential_type', sqlite_where=sa.text("status IN ('queued', 'running', 'waiting_quota')"))
        batch_op.drop_index(batch_op.f('ix_operation_status'))
        batch_op.drop_index(batch_op.f('ix_operation_credential_id'))

    op.drop_table('operation')
    with op.batch_alter_table('job_trigger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_trigger_status'))
        batch_op.drop_index(batch_op.f('ix_job_trigger_job_id'))

    op.drop_table('job_trigger')
    with op.batch_alter_table('deletion_tombstone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deletion_tombstone_title'))
        batch_op.drop_index(batch_op.f('ix_deletion_tombstone_repository_id'))
        batch_op.drop_index(batch_op.f('ix_deletion_tombstone_deleted_at'))

    op.drop_table('deletion_tombstone')
    with op.batch_alter_table('backup_subtask', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_subtask_status'))
        batch_op.drop_index(batch_op.f('ix_backup_subtask_repository_id'))
        batch_op.drop_index(batch_op.f('ix_backup_subtask_job_id'))
        batch_op.drop_index(batch_op.f('ix_backup_subtask_credential_id'))

    op.drop_table('backup_subtask')
    with op.batch_alter_table('admin_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_session_token_hash'))
        batch_op.drop_index(batch_op.f('ix_admin_session_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_admin_session_expires_at'))
        batch_op.drop_index(batch_op.f('ix_admin_session_admin_id'))

    op.drop_table('admin_session')
    with op.batch_alter_table('yuque_credential', schema=None) as batch_op:
        batch_op.drop_index('uq_yuque_credential_active_name', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_yuque_credential_status'))
        batch_op.drop_index(batch_op.f('ix_yuque_credential_next_retry_at'))
        batch_op.drop_index(batch_op.f('ix_yuque_credential_enabled'))
        batch_op.drop_index(batch_op.f('ix_yuque_credential_deleted_at'))

    op.drop_table('yuque_credential')
    op.drop_table('worker_heartbeat')
    op.drop_table('retention_policy')
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_selected'))

    op.drop_table('repository')
    with op.batch_alter_table('rate_limit_bucket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_bucket_next_allowed_at'))

    op.drop_table('rate_limit_bucket')
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempt_blocked_until'))

    op.drop_table('login_attempt')
    with op.batch_alter_table('idempotency_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_record_expires_at'))

    op.drop_table('idempotency_record')
    with op.batch_alter_table('backup_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_job_trigger'))
        batch_op.drop_index(batch_op.f('ix_backup_job_status'))
        batch_op.drop_index(batch_op.f('ix_backup_job_created_at'))

    op.drop_table('backup_job')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_sha256'))
        batch_op.drop_index(batch_op.f('ix_asset_purged_at'))

    op.drop_table('asset')
    op.drop_table('app_setting')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_username'))

    op.drop_table('admin')
    # ### end Alembic commands ###
